import './globals.css'
import type { Metadata } from 'next'
import { Josefin_Sans } from 'next/font/google'
import NavBar from './components/NavBar'
import AuthProvider from './context/AuthProvider'

const Josefin = Josefin_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Josefin.className}>
        <AuthProvider>
          <NavBar />
          <main className='flex min-h-screen items-start justify-center'>
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
